FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY frontend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# NO copiamos el código — se monta con bind-mount
EXPOSE 8050

CMD ["python", "app.py"]
