FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del backend
COPY backend /app

EXPOSE 8000

# Render no permite hot-reload, quitamos --reload
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
