services:
  - name: quint-backend
    type: web
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: SQLITE_PATH
        value: /app/data/tfg.db
      - key: REDIS_HOST
        fromService:
          name: quint-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: quint-redis
          type: redis
          property: port
      - key: REDIS_URL
        fromService:
          name: quint-redis
          type: redis
          property: connectionString

  - name: quint-frontend
    type: web
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile.frontend
    envVars:
      - key: BACKEND_URL
        value: https://quint-backend.onrender.com

  - name: quint-redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0